Pages/Borrowings/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using proiect.Data;
using proiect.Models;

namespace proiect.Pages.Borrowings
{
    public class CreateModel : PageModel
    {
        private readonly proiect.Data.proiectContext _context;

        public CreateModel(proiect.Data.proiectContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            var movieList = _context.Movie
                .Include(b => b.Director)
                .Select(x => new
            {
                 x.ID,
                 MovieFullName = x.Title + " - " + x.Director.LastName + " " + x.Director.FirstName});

            ViewData["MovieID"] = new SelectList(movieList, "ID", "MovieFullName");
            ViewData["MemberID"] = new SelectList(_context.Member, "ID", "FullName");
            return Page();
        }

        [BindProperty]
        public Borrowing Borrowing { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Borrowing == null || Borrowing == null)
            {
                return Page();
            }

            _context.Borrowing.Add(Borrowing);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Borrowings/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using proiect.Data;
using proiect.Models;

namespace proiect.Pages.Borrowings
{
    public class DeleteModel : PageModel
    {
        private readonly proiect.Data.proiectContext _context;

        public DeleteModel(proiect.Data.proiectContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Borrowing Borrowing { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Borrowing == null)
            {
                return NotFound();
            }

            var borrowing = await _context.Borrowing.FirstOrDefaultAsync(m => m.ID == id);

            if (borrowing == null)
            {
                return NotFound();
            }
            else 
            {
                Borrowing = borrowing;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Borrowing == null)
            {
                return NotFound();
            }
            var borrowing = await _context.Borrowing.FindAsync(id);

            if (borrowing != null)
            {
                Borrowing = borrowing;
                _context.Borrowing.Remove(Borrowing);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Borrowings/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using proiect.Data;
using proiect.Models;

namespace proiect.Pages.Borrowings
{
    public class DetailsModel : PageModel
    {
        private readonly proiect.Data.proiectContext _context;

        public DetailsModel(proiect.Data.proiectContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            var movieList = _context.Movie
                .Include(b => b.Director)
                .Select(x => new
                {
                    x.ID,
                    MovieFullName = x.Title + " - " + x.Director.LastName + " " + x.Director.FirstName
                });

            ViewData["MovieID"] = new SelectList(movieList, "ID", "MovieFullName");
            ViewData["MemberID"] = new SelectList(_context.Member, "ID", "FullName");
            return Page();
        }

        public Borrowing Borrowing { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Borrowing == null)
            {
                return NotFound();
            }

            var borrowing = await _context.Borrowing.FirstOrDefaultAsync(m => m.ID == id);
            if (borrowing == null)
            {
                return NotFound();
            }
            else 
            {
                Borrowing = borrowing;
            }
            return Page();
        }
    }
}

Pages/Borrowings/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using proiect.Data;
using proiect.Models;

namespace proiect.Pages.Borrowings
{
    public class EditModel : PageModel
    {
        private readonly proiect.Data.proiectContext _context;

        public EditModel(proiect.Data.proiectContext context)
        {
            _context = context;
        }
        public IActionResult OnGet()
        {
            var movieList = _context.Movie
                .Include(b => b.Director)
                .Select(x => new
                {
                    x.ID,
                    MovieFullName = x.Title + " - " + x.Director.LastName + " " + x.Director.FirstName
                });

            ViewData["MovieID"] = new SelectList(movieList, "ID", "MovieFullName");
            ViewData["MemberID"] = new SelectList(_context.Member, "ID", "FullName");
            return Page();
        }

        [BindProperty]
        public Borrowing Borrowing { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Borrowing == null)
            {
                return NotFound();
            }

            var borrowing =  await _context.Borrowing.FirstOrDefaultAsync(m => m.ID == id);
            if (borrowing == null)
            {
                return NotFound();
            }
            Borrowing = borrowing;
           ViewData["MovieID"] = new SelectList(_context.Movie, "ID", "ID");
           ViewData["MemberID"] = new SelectList(_context.Member, "ID", "ID");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Borrowing).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!BorrowingExists(Borrowing.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool BorrowingExists(int id)
        {
          return (_context.Borrowing?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

Pages/Directors/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using proiect.Data;
using proiect.Models;

namespace proiect.Pages.Directors
{
    public class CreateModel : PageModel
    {
        private readonly proiect.Data.proiectContext _context;

        public CreateModel(proiect.Data.proiectContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Director Director { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Director == null || Director == null)
            {
                return Page();
            }

            _context.Director.Add(Director);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Directors/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using proiect.Data;
using proiect.Models;

namespace proiect.Pages.Directors
{
    public class DeleteModel : PageModel
    {
        private readonly proiect.Data.proiectContext _context;

        public DeleteModel(proiect.Data.proiectContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Director Director { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Director == null)
            {
                return NotFound();
            }

            var director = await _context.Director.FirstOrDefaultAsync(m => m.ID == id);

            if (director == null)
            {
                return NotFound();
            }
            else 
            {
                Director = director;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Director == null)
            {
                return NotFound();
            }
            var director = await _context.Director.FindAsync(id);

            if (director != null)
            {
                Director = director;
                _context.Director.Remove(Director);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Directors/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using proiect.Data;
using proiect.Models;

namespace proiect.Pages.Directors
{
    public class DetailsModel : PageModel
    {
        private readonly proiect.Data.proiectContext _context;

        public DetailsModel(proiect.Data.proiectContext context)
        {
            _context = context;
        }

      public Director Director { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Director == null)
            {
                return NotFound();
            }

            var director = await _context.Director.FirstOrDefaultAsync(m => m.ID == id);
            if (director == null)
            {
                return NotFound();
            }
            else 
            {
                Director = director;
            }
            return Page();
        }
    }
}

Pages/Directors/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using proiect.Data;
using proiect.Models;

namespace proiect.Pages.Directors
{
    public class EditModel : PageModel
    {
        private readonly proiect.Data.proiectContext _context;

        public EditModel(proiect.Data.proiectContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Director Director { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Director == null)
            {
                return NotFound();
            }

            var director =  await _context.Director.FirstOrDefaultAsync(m => m.ID == id);
            if (director == null)
            {
                return NotFound();
            }
            Director = director;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Director).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!DirectorExists(Director.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool DirectorExists(int id)
        {
          return (_context.Director?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

Pages/Genres/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using proiect.Data;
using proiect.Models;

namespace proiect.Pages.Genres
{
    [Authorize(Roles = "Admin")]
    public class CreateModel : PageModel
    {
        private readonly proiect.Data.proiectContext _context;

        public CreateModel(proiect.Data.proiectContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Genre Genre { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Genre == null || Genre == null)
            {
                return Page();
            }

            _context.Genre.Add(Genre);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Movies/Details.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using proiect.Areas.Identity.Data;
using proiect.Models;

namespace proiect.Pages.Movies
{
    public class DetailsModel : PageModel
    {
        private readonly LibraryIdentityContext _identityContext;
        private readonly proiect.Data.proiectContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public DetailsModel(proiect.Data.proiectContext context, LibraryIdentityContext identityContext, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _identityContext = identityContext;
            _userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
        }

        public Movie Movie { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Movie == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .Include(m => m.Reviews)
                .FirstOrDefaultAsync(m => m.ID == id);

            if (movie == null)
            {
                return NotFound();
            }
            else
            {
                Movie = movie;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostDeleteReviewAsync(int reviewId, int movieId)
        {
            var review = await _context.Review.FindAsync(reviewId);

            if (review == null)
            {
                return NotFound();
            }

            _context.Review.Remove(review);
            await _context.SaveChangesAsync();

            return RedirectToPage("/Movies/Details", new { id = movieId });
        }
    }
}

Pages/Movies/Create.cshtml
@page
@model proiect.Pages.Movies.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                 <label asp-for="CoverArt" class="control-label">Cover Art</label>
                 <input type="file" asp-for="CoverArt" class="form-control" />
                 <span asp-validation-for="CoverArt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.Title" class="control-label"></label>
                <input asp-for="Movie.Title" class="form-control" />
                <span asp-validation-for="Movie.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.BoxOffice" class="control-label"></label>
                <input asp-for="Movie.BoxOffice" class="form-control" />
                <span asp-validation-for="Movie.BoxOffice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.Budget" class="control-label"></label>
                <input asp-for="Movie.Budget" class="form-control" />
                <span asp-validation-for="Movie.Budget" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.ReleaseDate" class="control-label"></label>
                <input asp-for="Movie.ReleaseDate" class="form-control" />
                <span asp-validation-for="Movie.ReleaseDate" class="textdanger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.ProducerID" class="control-label">Producer Name</label>
                <select asp-for="Movie.ProducerID" class="form-control" asp-items="ViewBag.ProducerID">
                </select>
                <span asp-validation-for="Movie.ProducerID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.DirectorID" class="control-label">Director Name</label>
                <select asp-for="Movie.DirectorID" class="form-control" asp-items="ViewBag.DirectorID">
                </select>
                <span asp-validation-for="Movie.DirectorID" class="text-danger"></span>
            </div>
            <div class="form-group">
                 <div class="table">
                    <table>
                         <tr>
                             @{
                                 int cnt = 0;       

                                 foreach (var gen in Model.AssignedGenreDataList)
                                 {
                                    if (cnt++ % 3 == 0)
                                    {
                                    @:</tr><tr>
                                    }
                                    @:<td>
                                    <input type="checkbox"
                                           name="selectedGenres"
                                           value="@gen.GenreID"
                                           @(Html.Raw(gen.Assigned ?
                                                "checked=\"checked\"" : "")) />
                                   @gen.GenreID @: @gen.Name
                               @:</td>
                            }
                         @:</tr>
                         }
                    </table>
                </div>
            </div>
               <div class="form-group">
         <input type="submit" value="Create" class="btn btn-primary" />
              </div>
         </form>
    </div>
 </div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Movies/Delete.cshtml
@page
@model proiect.Pages.Movies.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.CoverArtPath)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.CoverArtPath)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.BoxOffice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.BoxOffice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Budget)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Budget)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.ReleaseDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.ReleaseDate)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Movie.ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Pages/Movies/Details.cshtml
@page
@model proiect.Pages.Movies.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.CoverArtPath)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.CoverArtPath)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.BoxOffice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.BoxOffice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Budget)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Budget)
         </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.ReleaseDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.ReleaseDate)
       </dd>
    </dl>
</div>
<h2>Reviews</h2>
@if (Model.Movie.Reviews != null && Model.Movie.Reviews.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>Reviewer</th>
                <th>Comment</th>
                <th>Rating</th>
                <th>Action</th> 
            </tr>
        </thead>
        <tbody>
            @foreach (var review in Model.Movie.Reviews)
            {
                <tr>
                    <td>@review.User</td>
                    <td>@review.Comment</td>
                    <td>@review.Rating</td>
                    <td>
                        <form method="post" asp-page-handler="DeleteReview" asp-route-reviewId="@review.ID" asp-route-movieId="@Model.Movie.ID" onsubmit="return confirm('Are you sure you want to delete this review?');">
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>No reviews available for this movie.</p>
}

<a asp-page="/Reviews/CreateReview" asp-route-movieId="@Model.Movie.ID" class="btn btn-primary">Add Review</a>

<div>
    <a asp-page="./Edit" asp-route-id="@Model.Movie?.ID">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Pages/Movies/Edit.cshtml
@page
@model proiect.Pages.Movies.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Movie.ID" />
                <div class="form-group">
                 <label asp-for="CoverArt" class="control-label">Cover Art</label>
                 <input type="file" asp-for="CoverArt" class="form-control" />
                 <span asp-validation-for="CoverArt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.Title" class="control-label"></label>
                <input asp-for="Movie.Title" class="form-control" />
                <span asp-validation-for="Movie.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.BoxOffice" class="control-label"></label>
                <input asp-for="Movie.BoxOffice" class="form-control" />
                <span asp-validation-for="Movie.BoxOffice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.Budget" class="control-label"></label>
                <input asp-for="Movie.Budget" class="form-control" />
                <span asp-validation-for="Movie.Budget" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.ProducerID" class="control-label">Producer Name</label>
                <select asp-for="Movie.ProducerID" class="form-control" asp-items="ViewBag.ProducerID">
                </select>
                <span asp-validation-for="Movie.ProducerID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.DirectorID" class="control-label">Director Name</label>
                <select asp-for="Movie.DirectorID" class="form-control" asp-items="ViewBag.DirectorID">
                </select>
                <span asp-validation-for="Movie.DirectorID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="table">
                    <table>
                     <tr>
                            @{
                                int cnt = 0;

                                foreach (var gen in Model.AssignedGenreDataList)
                                {
                                    if (cnt++ % 3 == 0)
                                    {
                                        @:</tr><tr>
                                    }
                                    @:<td>
                                        <input type="checkbox"
                                               name="selectedGenres"
                                               value="@gen.GenreID"
                                               @(Html.Raw(gen.Assigned ? "checked=\"checked\"" : "")) />
                                         @gen.GenreID @: @gen.Name
                                    @:</td>
                                }
                            @:</tr>
                            }
                            </table>
                        </div>
                    </div>
                                <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}